[build]
  functions = "src/functions"

[context.production]
  command = "yarn build"
  publish = "public"

[context.deploy-preview]
  command = "yarn dev:build"
  publish = "build"

[context.develop]
  command = "yarn dev:clean && yarn dev:build"
  publish = "build"

[[redirects]]
  from = "https://localweather-io.netlify.com/*"
  to = "https://localweather.io/:splat"
  status = 301

[[redirects]]
  from = "https://dev-localweather-io.netlify.com/*"
  to = "https://dev.localweather.io/:splat"
  status = 301