[build]
  functions = "lambda"

[context.production]
  command = "yarn build"
  publish = "public"

[[redirects]]
  from = "https://localweather-io.netlify.com/*"
  to = "https://localweather.io/:splat"
  status = 301
